### ISSUE TITLE
Stop using usr/etc

### ISSUE THREAD

**Issue by cgwalters** [NERSC/podman-hpc#125]
See https://github.com/containers/bootc/issues/942

This is currently used as an implementation detail of ostree, and your usage of it conflicts. We may eventually lift this restriction, however, usage of `usr/etc` is very rare and it's generally been easier to get people to avoid conflicts. What are you doing with it?

**Comment by danfulton** [comment]
Hi Chris, we've addressed this in https://github.com/NERSC/podman-hpc/pull/126 

CC @rainest
