### ISSUE TITLE
writing conf files deprecated, set `ignore_chown_errors` in SiteConfig

### ISSUE THREAD

**Issue by lastephey** [NERSC/podman-hpc#30]
Parts of https://github.com/NERSC/podman-hpc/blob/main/podman_hpc/siteconfig.py are deprecated, including the parts that write a `storage.conf` and a `containers.conf`. 

We need to set the parameter `ignore_chown_errors` in the SiteConfig.

**Comment by danfulton** [comment]
Resolved by #45
