### ISSUE TITLE
Two `etc` config directories created during RPM installation.

### ISSUE THREAD

**Issue by danfulton** [NERSC/podman-hpc#31]
Two directories `/etc/podman-hpc` and `/etc/podman_hpc` created in RPM installation.  One of these is a symlink to `/usr/etc/podman-hpc`, which I think is an artifact of the earlier attempt to reconcile the desired RPM installation behaviour with the python package installation.  Alternatively, this could have something to do with the Ansible play, and should be handled in a NERSC internal issue.

Assuming it is an issue with the RPM, the quick fix here is fixing the line in the Makefile so that only one location is created.  But we probably need to go through code itself and make sure the directory that is used internally is the same as whatever the RPM specifies.  It would simplify things as well if the internal reference is only written out in one place, and passed with a variable reference when it is used elsewhere.

**Comment by lastephey** [comment]
Ah- it is partially a problem in ansible. I changed the dirs from hyphen to underscore in all but one place:

https://gitlab.nersc.gov/nersc/csg/nersc-cle/-/blob/development/shasta/ansible/nersc/roles/nersc-podman/tasks/main.yaml

We do create the `/etc/podman-hpc` dir, but we copy all files into the `/etc/podman_hpc` dir. I'll create an issue in our internal repo to remove the creation of the `/etc/podman-hpc` directory. 

Nothing in the ansible sets up a symlink, as far as I can see. That may be happening in the rpm.

**Comment by danfulton** [comment]
Right, I was doing that in the RPM to trick python, which wants to use a single install root e.g. either
`/usr/etc`, `/usr/lib`, `/usr/share`
OR
`/etc`,`/lib`,`/share`

But now that the RPM isn't installing the modules dir, it shouldn't be necessary any more.

**Comment by danfulton** [comment]
I believe this was fixed a while back!
