### ISSUE TITLE
Can I use podman-hpc on other HPC platform?

### ISSUE THREAD

**Issue by Zihe33Huang** [NERSC/podman-hpc#75]
Hi,

I am trying to install podman-hpc on Archer2, when I run `rpmbuild -ba podman-hpc.spec`  it occured that 

```
RPM build errors:
    File not found: /home/rpmbuild/BUILDROOT/podman-hpc-1.0.2-1.x86_64/usr/lib/python3.6/site-packages/podman_hpc*
```

**Comment by danfulton** [comment]
Thanks for your interest!  We have not had the opportunity to test installations at other sites yet, but in principle it should work.  Did you run the script `rpmsrcprep.sh` before running `rpmbuild`?

If you are running on a SUSE based system, you may also try to install the RPM provided on our release page.

**Comment by scanon** [comment]
Is archer2 also a Cray/HPE system?

**Comment by Zihe33Huang** [comment]
> 

Yes sir, it is.   ref: https://docs.archer2.ac.uk/

**Comment by Zihe33Huang** [comment]
> Thanks for your interest! We have not had the opportunity to test installations at other sites yet, but in principle it should work. Did you run the script `rpmsrcprep.sh` before running `rpmbuild`?
> 
> If you are running on a SUSE based system, you may also try to install the RPM provided on our release page.

Yes, I followed the site installation instructions in README.md,  could this be related to my system settings, like module load or something? because when this error occurs,
```
RPM build errors:
    File not found: /home/rpmbuild/BUILDROOT/podman-hpc-1.0.2-1.x86_64/usr/lib/python3.6/site-packages/podman_hpc*
``` 
the actual path is like "/usr/lib/python3.10/"   rather than "python3.6".

**Comment by danfulton** [comment]
> the actual path is like "/usr/lib/python3.10/"   rather than "python3.6".

I believe that path is determined by the `rpmbuild` variable `%{python3_sitelib}` in the rpm spec file.  What does that evaluate to on Archer 2?  On Perlmutter it looks like:
```
perlmutter> rpmbuild --eval "%{python3_sitelib}"
/usr/lib/python3.6/site-packages
```

**Comment by scanon** [comment]
Closing due to no response.
