### ISSUE TITLE
`--log-level error` not honored when pulling

### ISSUE THREAD

**Issue by wholtz** [NERSC/podman-hpc#76]
```bash
wjholtz@login30:~$ podman-hpc --log-level error pull -q \
>   'docker.io/doejgi/jamo-usa:latest' > /dev/null
WARN[0000] "/" is not a shared mount, this could cause issues or missing mounts with rootless containers 
```

I am trying to hide this `WARN` message from users of a script. I expected that `--log-level error` would result in the repression of this warning.

**Comment by lastephey** [comment]
Should be addressed by https://github.com/NERSC/podman-hpc/pull/82
